//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.Admin
{
    public partial class Departments
    {
        protected global::System.Web.UI.UpdatePanel updDepartments;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.Label lblErr;
        protected global::System.Web.UI.WebControls.Panel pnlEditor;
        protected global::System.Web.UI.WebControls.Literal litEditorTitle;
        protected global::System.Web.UI.WebControls.LinkButton lbCloseEditor;
        protected global::System.Web.UI.WebControls.HiddenField hfDepartmentID;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.TextBox txtOrder;
        protected global::System.Web.UI.WebControls.CheckBox chkActive;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Button btnAddNew;
        protected global::System.Web.UI.WebControls.GridView gvDepartments;
    }
}
