//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.Admin
{
    public partial class Roles
    {
        protected global::System.Web.UI.UpdatePanel updRoles;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.Label lblErr;
        protected global::System.Web.UI.WebControls.Button btnAddRole;
        protected global::System.Web.UI.WebControls.Panel pnlRoleEditor;
        protected global::System.Web.UI.WebControls.HiddenField hfRoleID;
        protected global::System.Web.UI.WebControls.TextBox txtRoleName;
        protected global::System.Web.UI.WebControls.Button btnSaveRole;
        protected global::System.Web.UI.WebControls.Button btnCancelRole;
        protected global::System.Web.UI.WebControls.GridView gvRoles;
        protected global::System.Web.UI.WebControls.DropDownList ddlRightsRole;
        protected global::System.Web.UI.WebControls.Panel pnlRights;
        protected global::System.Web.UI.WebControls.Repeater rptRights;
        protected global::System.Web.UI.WebControls.Button btnSaveRights;
        protected global::System.Web.UI.WebControls.Panel pnlNoRole;
    }
}
