//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.Deals
{
    public partial class CreateDeals
    {
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.UpdatePanel updDeal;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.Label lblErr;
        protected global::System.Web.UI.WebControls.HiddenField hfDealID;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlDealType;
        protected global::System.Web.UI.WebControls.Panel pnlDiscount;
        protected global::System.Web.UI.WebControls.Literal litValueLabel;
        protected global::System.Web.UI.WebControls.TextBox txtDiscountValue;
        protected global::System.Web.UI.WebControls.Panel pnlBundle;
        protected global::System.Web.UI.WebControls.TextBox txtDealPrice;
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.Repeater rptDealCats;
        protected global::System.Web.UI.WebControls.Panel pnlNoItems;
        protected global::System.Web.UI.WebControls.CheckBox chkActive;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnReset;
    }
}
