//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.Deals
{
    public partial class DealsList
    {
        protected global::System.Web.UI.UpdatePanel updDeals;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.Label lblErr;
        protected global::System.Web.UI.WebControls.LinkButton lbAll;
        protected global::System.Web.UI.WebControls.LinkButton lbActive;
        protected global::System.Web.UI.WebControls.LinkButton lbInactive;
        protected global::System.Web.UI.WebControls.GridView gvDeals;
    }
}
