//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS {


    public partial class _Default {

        protected global::System.Web.UI.WebControls.Literal litGreeting;
        protected global::System.Web.UI.WebControls.Literal litTodayVisits;
        protected global::System.Web.UI.WebControls.Literal litTodaySales;
        protected global::System.Web.UI.WebControls.Literal litUnread;
        protected global::System.Web.UI.WebControls.Literal litMenuCount;
        protected global::System.Web.UI.WebControls.Literal litPendingFulfil;
        protected global::System.Web.UI.WebControls.Literal litSalesThisMonth;
        protected global::System.Web.UI.WebControls.Literal litSalesLastMonth;
        protected global::System.Web.UI.WebControls.Literal litCompletionPct;
        protected global::System.Web.UI.WebControls.Literal litDineInPct;
        protected global::System.Web.UI.WebControls.Literal litTakeawayPct;
        protected global::System.Web.UI.WebControls.Literal litDeliveryPct;
        protected global::System.Web.UI.WebControls.Literal litTotalOrdersCenter;
        protected global::System.Web.UI.WebControls.Literal litWeeklySales;
        protected global::System.Web.UI.WebControls.Literal litTotalOrder;
        protected global::System.Web.UI.WebControls.Literal litOrders;
        protected global::System.Web.UI.WebControls.Literal litItemsSold;
        protected global::System.Web.UI.WebControls.Literal litCancelled;
        protected global::System.Web.UI.WebControls.Literal litGrossSale;
        protected global::System.Web.UI.WebControls.Literal litAvgOrder;
        protected global::System.Web.UI.WebControls.Literal litProcessing;
        protected global::System.Web.UI.WebControls.Repeater rptBreakdown;
        protected global::System.Web.UI.WebControls.Repeater rptRecent;
        protected global::System.Web.UI.WebControls.Literal litBestTotalOrders;
        protected global::System.Web.UI.WebControls.Repeater rptBest;
    }
}
